-- OTP inscription email
ALTER TABLE users ADD COLUMN IF NOT EXISTS otp_code VARCHAR(10);
ALTER TABLE users ADD COLUMN IF NOT EXISTS otp_expires_at TIMESTAMP WITH TIME ZONE;

-- 2FA login admin
ALTER TABLE users ADD COLUMN IF NOT EXISTS two_fa_code VARCHAR(10);
ALTER TABLE users ADD COLUMN IF NOT EXISTS two_fa_expires_at TIMESTAMP WITH TIME ZONE;
