-- Store server-generated user private keys to enable PKCS#12 export (.p12/.pfx)
-- NOTE: this is only populated when CSR is generated by the backend.

ALTER TABLE certificate_requests
    ADD COLUMN IF NOT EXISTS server_private_key_pem TEXT;

ALTER TABLE certificates
    ADD COLUMN IF NOT EXISTS private_key_pem TEXT;
